### ISSUE TITLE
Remove highlighted text

### ISSUE THREAD

**Issue by icaroperseo** [n8chz/prostetnic-chrome#1]
Is there any way to do this right now?

**Comment by n8chz** [comment]
Probably not in an elegant way.  It seems [WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contextMenus/ContextType) does not implement the [`SelectorContext`](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/context-menu#SelectorContext(selector)) that was a feature of the Add-on SDK, which unfortunately is being phased out (or never existed, if you're using the Chrome version).  Basically, WebExtensions provides no tool to know whether the cursor is inside a highlight element.

**Comment by n8chz** [comment]
While there is no selector context for WebExtensions context menus, it should be possible to get this behavior with [HTML context menus](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contextmenu), but that is [only supported on Firefox](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contextmenu#Browser_compatibility).

**Comment by icaroperseo** [comment]
I got it, thanks a lot and go ahead! :+1: 

Best regards.

**Comment by n8chz** [comment]
Make if a couple of weeks.  Doing it right will require a different data model.  This will also (probably) mean loss of data from versions before the change.

**Comment by n8chz** [comment]
Sorry about the long couple of weeks.  At this point (version 0.0.8) it's available for Firefox.  Hope it works for you.

**Comment by icaroperseo** [comment]
Thanks a lot for your dedication! I'm currently using it and I haven't any issue so far. Thanks again!

Best regards.
